### ISSUE TITLE
here

### ISSUE THREAD

**Issue by 12-malak** [12-malak/hbn#1]
here is the new feature

```
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  carbonate:
    runs-on: ubuntu-latest
    name: Generate beautiful images for code blocks present in issues
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate beautiful images for code blocks present in issues
        uses: ./
        id: carbonate
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          imgur-client-id: ${{ secrets.IMGUR_CLIENT_ID }}
```
